name: Local
variables:
  - name: baseUrl
    value: http://localhost:3000/api
  - name: username
    value: testing
  - secret: true
    name: password
  - secret: true
    name: token
  - name: id
    value: "6"
